### PR TITLE
Fix deprecation warnings and test failures

### PR DESCRIPTION
**Pull request by jamescook**
@ltk

### CODE REVIEW

**Comment by ltk** [comment]
I'm trying to replicate that Bcrypt issue I had before to see if it's a real thing. One moment please.

**Comment by ltk** [comment]
:+1: minus the weird diff at the bottom.

**Comment by tommymarshall** [comment]
:thumbsup: for jaems.

**Comment by reagent** [comment]
Hay. I've been reworking this for multiple user authentication and to make it compatible with Rails4 in a [separate branch](https://github.com/vigetlabs/simplest_auth/compare/rails-4).  I can't pull this in, but I've made those changes there.

**Pull request closed without merging**
